export type Language = 'en' | 'es' | 'fr' | 'de' | 'ja' | 'te' | 'hi' | 'ta';

export interface TranslationSet {
  brand: string;
  tagline: string;
  searchPlaceholder: string;
  allCategories: string;
  smartRecs: string;
  analytics: string;
  dashboard: string;
  cart: string;
  login: string;
  register: string;
  logout: string;
  adminPanel: string;
  categories: string;
  addToCart: string;
  outOfStock: string;
  rating: string;
  inStock: string;
  onlyLeft: string;
  features: string;
  specs: string;
  checkoutSummary: string;
  orderTotal: string;
  paymentDetails: string;
  cardNumber: string;
  expiryDate: string;
  shippingAddress: string;
  fullName: string;
  addressLines: string;
  city: string;
  postalCode: string;
  country: string;
  deliveryPartner: string;
  placeOrder: string;
  orderSuccess: string;
  orderSuccessDesc: string;
  trackingId: string;
  estimatedDelivery: string;
  customerCabinet: string;
  noOrders: string;
  orderId: string;
  orderDate: string;
  orderStatus: string;
  paymentStatus: string;
  carrier: string;
  trackShipment: string;
  salesReporting: string;
  totalSales: string;
  totalOrdersCount: string;
  lowStockAlerts: string;
  salesByCategory: string;
  dailyRevenueTrend: string;
  topPerformingItems: string;
  notifications: string;
  markAllRead: string;
  noNotifications: string;
  toggleTheme: string;
  languageLabel: string;
  backToProducts: string;
  recReasonPrompt: string;
  confidenceScore: string;
  aiEngineStatus: string;
  shippingProgress: string;
  changeStatus: string;
  updateStatusBtn: string;
  filters: string;
  reset: string;
  productCategory: string;
  allElectronics: string;
  minPrice: string;
  maxPrice: string;
  filterByBrand: string;
  noBrandsFound: string;
  minimumRating: string;
  allRatings: string;
  andUp: string;
  authQuickDemo: string;
  authAutofill: string;
  authOrRegisterDesc: string;
  yourFullName: string;
  emailAddress: string;
  securePassword: string;
  alreadyRegistered: string;
  createNewProfile: string;
  verifiedAccountsFeedback: string;
  aggregateScore: string;
  basedOnReviews: string;
  verifiedOwner: string;
  writeReview: string;
  yourRating: string;
  yourExperience: string;
  submitReviewBtn: string;
  reviewLocked: string;
  authRequiredToLeaveFeedback: string;
  feedbackWritesRequireVerification: string;
  activeRecoup: string;
  itemsPurchased: string;
  grossTotal: string;
  recipientAddress: string;
  showcaseTrackingUpdates: string;
  carrierLabel: string;
  trackingNumberLabel: string;
  zeroUpfrontCharge: string;
  fastConfirmedShipping: string;
  paymentVerifyTxt: string;
  backToCart: string;
  cartPriceLabel: string;
  viewSpecsDetail: string;
  productShowcase: string;
}

export const translations: Record<Language, TranslationSet> = {
  en: {
    brand: 'NexCart',
    tagline: 'Precision Engineered High-Tech Electronics',
    searchPlaceholder: 'Search smartphones, high-spec laptops, audio gear...',
    allCategories: 'All Categories',
    smartRecs: 'Smart AI Recs',
    analytics: 'Sales Analytics',
    dashboard: 'Dashboard',
    cart: 'Shopping Cart',
    login: 'Log In',
    register: 'Sign Up',
    logout: 'Log Out',
    adminPanel: 'Admin Panel',
    categories: 'Categories',
    addToCart: 'Add To Cart',
    outOfStock: 'Sold Out',
    rating: 'Rating',
    inStock: 'In Stock',
    onlyLeft: 'Only left',
    features: 'Key Features',
    specs: 'Technical Specifications',
    checkoutSummary: 'Checkout Summary',
    orderTotal: 'Order Total',
    paymentDetails: 'Secure Payment Gateway',
    cardNumber: 'Credit Card Number',
    expiryDate: 'Expiry Date (MM/YY)',
    shippingAddress: 'Shipping Address',
    fullName: 'Full Name',
    addressLines: 'Street Address',
    city: 'City',
    postalCode: 'Postal Code',
    country: 'Country',
    deliveryPartner: 'Logistics Partner',
    placeOrder: 'Authorize Secure Payment',
    orderSuccess: 'Payment Authorized Successfully!',
    orderSuccessDesc: 'Your order was processed. Real-time stock levels have been updated and logistics tracking is live.',
    trackingId: 'Logistics Tracking ID',
    estimatedDelivery: 'Estimated Delivery',
    customerCabinet: 'Customer Dashboard',
    noOrders: 'You have no registered transactions yet.',
    orderId: 'Order ID',
    orderDate: 'Date',
    orderStatus: 'Shipping Status',
    paymentStatus: 'Payment',
    carrier: 'Logistics Courier',
    trackShipment: 'Track Shipping Route',
    salesReporting: 'Admin Financial Sales Analytics',
    totalSales: 'Gross Sales Revenue',
    totalOrdersCount: 'Total Orders',
    lowStockAlerts: 'Low Stock Alert Trigger',
    salesByCategory: 'Sales Revenue by Product Category (INR)',
    dailyRevenueTrend: 'Daily Revenue Curve (INR)',
    topPerformingItems: 'Top Performing Products (by units sold)',
    notifications: 'Real-Time Notifications',
    markAllRead: 'Mark All as Read',
    noNotifications: 'You are completely caught up.',
    toggleTheme: 'Toggle Visual Theme',
    languageLabel: 'Select Language',
    backToProducts: 'Back to Showcase',
    recReasonPrompt: 'AI Recommended Reason',
    confidenceScore: 'AI Match Confidence',
    aiEngineStatus: 'Powered by server-side Gemini 3.5-Flash',
    shippingProgress: 'Standard Courier Dispatch Progress',
    changeStatus: 'Modify Transit Status (Admin command)',
    updateStatusBtn: 'Update Status',
    filters: 'Filters',
    reset: 'Reset',
    productCategory: 'Product Category',
    allElectronics: 'All Electronics',
    minPrice: 'Min Price',
    maxPrice: 'Max Price',
    filterByBrand: 'Filter by Brand',
    noBrandsFound: 'No brands found.',
    minimumRating: 'Minimum Rating',
    allRatings: 'All Ratings',
    andUp: '& Up',
    authQuickDemo: 'Quick Demo Credentials:',
    authAutofill: 'Autofill',
    authOrRegisterDesc: 'Or register a brand new customer profile to trigger first welcome notifications!',
    yourFullName: 'Your Full Name',
    emailAddress: 'Email Address',
    securePassword: 'Secure Pin / Password',
    alreadyRegistered: 'Already registered? Sign In',
    createNewProfile: 'Create a brand new profile instead',
    verifiedAccountsFeedback: 'Verified Accounts Feedback',
    aggregateScore: 'AGGREGATE SCORE',
    basedOnReviews: 'Based on verified corporate or individual purchasers.',
    verifiedOwner: 'Verified Owner',
    writeReview: 'Write your review for',
    yourRating: 'YOUR RATING',
    yourExperience: 'YOUR EXPERIENCE',
    submitReviewBtn: 'Submit Verified Review',
    reviewLocked: 'Write Review Locked',
    authRequiredToLeaveFeedback: 'Authentication is required to leave feedback. Please sign in or register above, purchase this tech item, and verify your receipt to leave reviews.',
    feedbackWritesRequireVerification: 'Feedback writes require verification of product ownership. Place an order containing this item first to unlock feedback submissions.',
    activeRecoup: 'ACTIVE RECOUP',
    itemsPurchased: 'Items Purchased',
    grossTotal: 'Gross Total',
    recipientAddress: 'Recipient Address',
    showcaseTrackingUpdates: 'Showcase tracking updates. Select order...',
    carrierLabel: 'Carrier',
    trackingNumberLabel: 'Tracking Number',
    zeroUpfrontCharge: 'Zero Upfront Charge',
    fastConfirmedShipping: 'Fast confirmed shipping. Safe sandbox COD verification.',
    paymentVerifyTxt: 'Verifying payment...',
    backToCart: 'Back to Cart',
    cartPriceLabel: 'PRICE',
    viewSpecsDetail: 'View Details Specs',
    productShowcase: '🛒 Product Showcase'
  },
  es: {
    brand: 'NexCart',
    tagline: 'Electrónica de alta tecnología diseñada con precisión',
    searchPlaceholder: 'Buscar teléfonos inteligentes, computadoras portátiles...',
    allCategories: 'Todas las Categorías',
    smartRecs: 'IA Recomendaciones',
    analytics: 'Analítica de Ventas',
    dashboard: 'Mi Panel',
    cart: 'Mi Carrito',
    login: 'Iniciar Sesión',
    register: 'Registrarse',
    logout: 'Cerrar Sesión',
    adminPanel: 'Panel de Admin',
    categories: 'Categorías',
    addToCart: 'Agregar al Carrito',
    outOfStock: 'Agotado',
    rating: 'Calificación',
    inStock: 'En Stock',
    onlyLeft: 'Solo quedan',
    features: 'Características Clave',
    specs: 'Especificaciones Técnicas',
    checkoutSummary: 'Resumen Financiero',
    orderTotal: 'Total del Pedido',
    paymentDetails: 'Pasarela de Pago Segura',
    cardNumber: 'Número de Tarjeta',
    expiryDate: 'Fecha de Expiración (MM/AA)',
    shippingAddress: 'Dirección de Entrega',
    fullName: 'Nombre Completo',
    addressLines: 'Calle y Número',
    city: 'Ciudad',
    postalCode: 'Código Postal',
    country: 'País',
    deliveryPartner: 'Socio Logístico',
    placeOrder: 'Autorizar Pago Seguro',
    orderSuccess: '¡Pago Autorizado Exitosamente!',
    orderSuccessDesc: 'Su pedido fue procesado. Los niveles de inventario se actualizaron y el rastreo está en vivo.',
    trackingId: 'ID de Rastreo Logístico',
    estimatedDelivery: 'Fecha Est. de Entrega',
    customerCabinet: 'Panel de Control del Cliente',
    noOrders: 'Aún no tiene transacciones registradas.',
    orderId: 'Pedido ID',
    orderDate: 'Fecha',
    orderStatus: 'Estado de Envío',
    paymentStatus: 'Pago',
    carrier: 'Mensajería Asignada',
    trackShipment: 'Seguir Ruta de Envío',
    salesReporting: 'Analítica Financiera de Ventas Corporativas',
    totalSales: 'Ingresos Brutos de Ventas',
    totalOrdersCount: 'Total de Pedidos',
    lowStockAlerts: 'Alerta de Inventario Crítico',
    salesByCategory: 'Ingresos por Categoría de Producto (INR)',
    dailyRevenueTrend: 'Curva de Ingresos Diarios (INR)',
    topPerformingItems: 'Productos Más Vendidos (por unidades)',
    notifications: 'Notificaciones en Tiempo Real',
    markAllRead: 'Marcar todo como leído',
    noNotifications: 'Está al día con todos los avisos.',
    toggleTheme: 'Cambiar Tema Visual',
    languageLabel: 'Seleccionar Idioma',
    backToProducts: 'Volver al Catálogo',
    recReasonPrompt: 'Razón de Recomendación IA',
    confidenceScore: 'Confianza de Ajuste IA',
    aiEngineStatus: 'Impulsado por Gemini 3.5-Flash (Servidor)',
    shippingProgress: 'Progreso del Despacho Logístico',
    changeStatus: 'Modificar Estado de Tránsito (Comando Admin)',
    updateStatusBtn: 'Actualizar Estado',
    filters: 'Filtros',
    reset: 'Restablecer',
    productCategory: 'Categoría de Producto',
    allElectronics: 'Todos los Electrónicos',
    minPrice: 'Precio Mínimo',
    maxPrice: 'Precio Máximo',
    filterByBrand: 'Filtrar por Marca',
    noBrandsFound: 'No se encontraron marcas.',
    minimumRating: 'Calificación Mínima',
    allRatings: 'Todas las Calificaciones',
    andUp: 'y superior',
    authQuickDemo: 'Credenciales rápidas de demostración:',
    authAutofill: 'Relleno automático',
    authOrRegisterDesc: '¡O regístrese para activar notificaciones de bienvenida!',
    yourFullName: 'Su Nombre Completo',
    emailAddress: 'Correo Electrónico',
    securePassword: 'Contraseña Pin Segura',
    alreadyRegistered: '¿Ya está registrado? Iniciar Sesión',
    createNewProfile: 'Crear un perfil nuevo en su lugar',
    verifiedAccountsFeedback: 'Comentarios de cuentas verificadas',
    aggregateScore: 'PUNTUACIÓN ACUMULATIVA',
    basedOnReviews: 'Basado en compradores corporativos o individuales verificados.',
    verifiedOwner: 'Propietario Verificado',
    writeReview: 'Escriba su opinión para',
    yourRating: 'SU CALIFICACIÓN',
    yourExperience: 'SU EXPERIENCIA',
    submitReviewBtn: 'Enviar opinión verificada',
    reviewLocked: 'Escritura de opinión bloqueada',
    authRequiredToLeaveFeedback: 'Se requiere autenticación para opinar. Inicie sesión, compre este artículo y verifique su recibo.',
    feedbackWritesRequireVerification: 'Las opiniones requieren verificar la propiedad. Realice un pedido de este artículo primero.',
    activeRecoup: 'LOGÍSTICA ACTIVA',
    itemsPurchased: 'Artículos Comprados',
    grossTotal: 'Total Bruto',
    recipientAddress: 'Dirección del Destinatario',
    showcaseTrackingUpdates: 'Seleccione un pedido para ver actualizaciones de rastreo...',
    carrierLabel: 'Transportista',
    trackingNumberLabel: 'ID de Rastreo',
    zeroUpfrontCharge: 'Sin cargos por adelantado',
    fastConfirmedShipping: 'Envío rápido confirmado. Verificación COD segura.',
    paymentVerifyTxt: 'Verificando pago...',
    backToCart: 'Volver al Carrito',
    cartPriceLabel: 'PRECIO',
    viewSpecsDetail: 'Ver especificaciones detalladas',
    productShowcase: '🛒 Catálogo de productos'
  },
  fr: {
    brand: 'NexCart',
    tagline: 'Électronique de Haute Technologie Conçue avec Précision',
    searchPlaceholder: 'Rechercher des smartphones, ordinateurs haut de gamme...',
    allCategories: 'Toutes Catégories',
    smartRecs: 'IA Recommandations',
    analytics: 'Analyses de Vente',
    dashboard: 'Tableau de Bord',
    cart: 'Panier d\'achats',
    login: 'Se Connecter',
    register: 'S\'inscrire',
    logout: 'Se Déconnecter',
    adminPanel: 'Portail Admin',
    categories: 'Catégories',
    addToCart: 'Ajouter au Panier',
    outOfStock: 'Épuisé',
    rating: 'Évaluation',
    inStock: 'En Stock',
    onlyLeft: 'Plus que',
    features: 'Caractéristiques Principales',
    specs: 'Spécifications Techniques',
    checkoutSummary: 'Récapitulatif de Commande',
    orderTotal: 'Total de Commande',
    paymentDetails: 'Passerelle de Paiement Sécurisée',
    cardNumber: 'Numéro de Carte',
    expiryDate: 'Date d\'Expiration (MM/AA)',
    shippingAddress: 'Adresse de Livraison',
    fullName: 'Nom Complet',
    addressLines: 'Rue et Numéro',
    city: 'Ville',
    postalCode: 'Code Postal',
    country: 'Pays',
    deliveryPartner: 'Partenaire Logistique',
    placeOrder: 'Autoriser le Paiement Sécurisé',
    orderSuccess: 'Paiement Autorisé avec Succès !',
    orderSuccessDesc: 'Votre commande a été traitée. Les stocks physiques ont été ajustés et le suivi logistique est activé.',
    trackingId: 'ID Suivi Logistique',
    estimatedDelivery: 'Livraison Estimée',
    customerCabinet: 'Tableau de Bord Client',
    noOrders: 'Aucune transaction enregistrée pour le moment.',
    orderId: 'ID de Commande',
    orderDate: 'Date',
    orderStatus: 'Statut d\'Expédition',
    paymentStatus: 'Paiement',
    carrier: 'Transporteur Attribué',
    trackShipment: 'Tracer l\'itinéraire de livraison',
    salesReporting: 'Analytique Financière des Ventes',
    totalSales: 'Chiffre d\'Affaires Brut',
    totalOrdersCount: 'Commandes Totales',
    lowStockAlerts: 'Seuils d\'Alerte de Stock Bas',
    salesByCategory: 'Chiffre d\'Affaires par Catégorie (INR)',
    dailyRevenueTrend: 'Courbe de Revenus Quotidiens (INR)',
    topPerformingItems: 'Produits Phares (unités vendues)',
    notifications: 'Notifications en Temps Réel',
    markAllRead: 'Tout marquer comme lu',
    noNotifications: 'Pas de nouveaux messages.',
    toggleTheme: 'Basculer le Thème Visuel',
    languageLabel: 'Choisir la Langue',
    backToProducts: 'Retour au Catalogue',
    recReasonPrompt: 'Motif de Recommandation IA',
    confidenceScore: 'Score de Confiance Intel IA',
    aiEngineStatus: 'Alimenté par Gemini 3.5-Flash côté serveur',
    shippingProgress: 'Avancement de la Livraison',
    changeStatus: 'Modifier le Statut d\'Expédition (Admin)',
    updateStatusBtn: 'Mettre à jour',
    filters: 'Filtres',
    reset: 'Réinitialiser',
    productCategory: 'Catégorie de produit',
    allElectronics: 'Tous les produits électroniques',
    minPrice: 'Prix minimum',
    maxPrice: 'Prix maximum',
    filterByBrand: 'Filtrer par marque',
    noBrandsFound: 'Aucune marque trouvée.',
    minimumRating: 'Note minimale',
    allRatings: 'Toutes les évaluations',
    andUp: 'et plus',
    authQuickDemo: 'Identifiants de démo rapides:',
    authAutofill: 'Remplissage automatique',
    authOrRegisterDesc: 'Ou créez un nouveau compte pour obtenir la notification de bienvenue!',
    yourFullName: 'Votre nom complet',
    emailAddress: 'Adresse e-mail',
    securePassword: 'Mot de passe sécurisé',
    alreadyRegistered: 'Déjà inscrit ? Se connecter',
    createNewProfile: 'Créer un nouveau profil à la place',
    verifiedAccountsFeedback: 'Commentaires des comptes vérifiés',
    aggregateScore: 'SCORE GLOBAL',
    basedOnReviews: 'Basé sur des acheteurs réels et vérifiés.',
    verifiedOwner: 'Propriétaire vérifié',
    writeReview: 'Écrire un avis pour',
    yourRating: 'VOTRE ÉVALUATION',
    yourExperience: 'VOTRE EXPÉRIENCE',
    submitReviewBtn: 'Envoyer l\'avis vérifié',
    reviewLocked: 'Rédaction d\'avis verrouillée',
    authRequiredToLeaveFeedback: 'Connexion requise. Veuillez vous connecter, acheter cet article et vérifier votre reçu.',
    feedbackWritesRequireVerification: 'Les avis nécessitent de posséder l\'article. Passez d\'abord une commande de cet article.',
    activeRecoup: 'LOGISTIQUE ACTIVE',
    itemsPurchased: 'Articles achetés',
    grossTotal: 'Total brut',
    recipientAddress: 'Adresse du destinataire',
    showcaseTrackingUpdates: 'Sélectionnez une commande pour suivre l\'expédition...',
    carrierLabel: 'Transporteur',
    trackingNumberLabel: 'Numéro de suivi',
    zeroUpfrontCharge: 'Aucuns frais initiaux',
    fastConfirmedShipping: 'Expédition rapide. Option de paiement à la livraison vérifiée.',
    paymentVerifyTxt: 'Vérification du paiement...',
    backToCart: 'Retour au panier',
    cartPriceLabel: 'PRIX',
    viewSpecsDetail: 'Voir les spécifications',
    productShowcase: '🛒 Vitrine produits'
  },
  de: {
    brand: 'NexCart',
    tagline: 'Präzisionsgefertigte High-Tech-Elektronik',
    searchPlaceholder: 'Suche nach Smartphones, High-End Laptops, Audio...',
    allCategories: 'Alle Kategorien',
    smartRecs: 'Smart AI Empfehlungen',
    analytics: 'Umsatzberichte',
    dashboard: 'Kundenkonto',
    cart: 'Warenkorb',
    login: 'Einloggen',
    register: 'Registrieren',
    logout: 'Ausloggen',
    adminPanel: 'Admin-Zentrale',
    categories: 'Kategorien',
    addToCart: 'In den Warenkorb',
    outOfStock: 'Ausverkauft',
    rating: 'Bewertung',
    inStock: 'Auf Lager',
    onlyLeft: 'Nur noch',
    features: 'Hauptmerkmale',
    specs: 'Technische Spezifikationen',
    checkoutSummary: 'Kassenbeleg-Übersicht',
    orderTotal: 'Gesamtsumme',
    paymentDetails: 'Sicheres Zahlungs-Gateway',
    cardNumber: 'Kreditkartennummer',
    expiryDate: 'Ablaufdatum (MM/JJ)',
    shippingAddress: 'Lieferadresse',
    fullName: 'Vollständiger Name',
    addressLines: 'Straße & Hausnummer',
    city: 'Stadt',
    postalCode: 'Postleitzahl',
    country: 'Land',
    deliveryPartner: 'Logistikpartner',
    placeOrder: 'Sicher bezahlen',
    orderSuccess: 'Zahlung erfolgreich autorisiert!',
    orderSuccessDesc: 'Ihre Bestellung wurde verbucht. Der Echtzeitbestand wurde angepasst und das Logistik-Tracking ist aktiv.',
    trackingId: 'Logistik-Tracking-ID',
    estimatedDelivery: 'Voraussichtliche Lieferung',
    customerCabinet: 'Kunden-Dashboard',
    noOrders: 'Sie haben noch keine abgeschlossenen Transaktionen.',
    orderId: 'Bestellnummer',
    orderDate: 'Datum',
    orderStatus: 'Lieferstatus',
    paymentStatus: 'Zahlung',
    carrier: 'Logistikdienstleister',
    trackShipment: 'Lieferroute verfolgen',
    salesReporting: 'Finanzielle Umsatzanalysen (Admin)',
    totalSales: 'Bruttoumsatz',
    totalOrdersCount: 'Bestellungen Gesamt',
    lowStockAlerts: 'Warnung bei geringem Bestand',
    salesByCategory: 'Umsatz nach Produktkategorie (INR)',
    dailyRevenueTrend: 'Tägliche Umsatzkurve (INR)',
    topPerformingItems: 'Meistverkaufte Produkte',
    notifications: 'Echtzeit-Benachrichtigungen',
    markAllRead: 'Alle als gelesen markieren',
    noNotifications: 'Keine neuen Benachrichtigungen.',
    toggleTheme: 'Visuelles Design umschalten',
    languageLabel: 'Sprachauswahl',
    backToProducts: 'Zurück zum Sortiment',
    recReasonPrompt: 'KI-Empfehlungsgrund',
    confidenceScore: 'KI-Übereinstimmung',
    aiEngineStatus: 'Präsentiert durch serverseitiges Gemini 3.5-Flash',
    shippingProgress: 'Lieferfortschritt des Express-Kuriers',
    changeStatus: 'Transportstatus anpassen (Admin-Befehl)',
    updateStatusBtn: 'Status aktualisieren',
    filters: 'Filter',
    reset: 'Zurücksetzen',
    productCategory: 'Produktkategorie',
    allElectronics: 'Alle Elektronikartikel',
    minPrice: 'Mindestpreis',
    maxPrice: 'Maximalpreis',
    filterByBrand: 'Nach Marke filtern',
    noBrandsFound: 'Keine Marken gefunden.',
    minimumRating: 'Mindestbewertung',
    allRatings: 'Alle Bewertungen',
    andUp: '& mehr',
    authQuickDemo: 'Schnelle Demo-Zugangsdaten:',
    authAutofill: 'Autom. ausfüllen',
    authOrRegisterDesc: 'Oder registrieren Sie ein neues Konto, um die Begrüßung zu erhalten!',
    yourFullName: 'Ihr vollständiger Name',
    emailAddress: 'E-Mail-Adresse',
    securePassword: 'Sicheres Passwort / PIN',
    alreadyRegistered: 'Bereits registriert? Einloggen',
    createNewProfile: 'Erstellen Sie stattdessen ein neues Profil',
    verifiedAccountsFeedback: 'Verifiziertes Kundenfeedback',
    aggregateScore: 'GESAMTBEWERTUNG',
    basedOnReviews: 'Basierend auf echten Käufern.',
    verifiedOwner: 'Verifizierter Käufer',
    writeReview: 'Bewertung schreiben für',
    yourRating: 'IHRE BEWERTUNG',
    yourExperience: 'IHRE ERFAHRUNG',
    submitReviewBtn: 'Verifizierte Bewertung senden',
    reviewLocked: 'Bewertung gesperrt',
    authRequiredToLeaveFeedback: 'Einloggen erforderlich, um Feedback zu hinterlassen. Melden Sie sich an und kaufen Sie das Produkt.',
    feedbackWritesRequireVerification: 'Bewertungen erfordern den Besitz des Produkts. Bestellen Sie zuerst diesen Artikel.',
    activeRecoup: 'AKTIVE LOGISTIK',
    itemsPurchased: 'Gekaufte Artikel',
    grossTotal: 'Gesamtsumme',
    recipientAddress: 'Empfängeradresse',
    showcaseTrackingUpdates: 'Wählen Sie eine Bestellung für Sendungsverfolgung...',
    carrierLabel: 'Logistikpartner',
    trackingNumberLabel: 'Trackingnummer',
    zeroUpfrontCharge: 'Keine Anzahlung erforderlich',
    fastConfirmedShipping: 'Schneller Versand. Sichere Nachnahme-Prüfung.',
    paymentVerifyTxt: 'Zahlung wird geprüft...',
    backToCart: 'Zurück zum Warenkorb',
    cartPriceLabel: 'PREIS',
    viewSpecsDetail: 'Details anzeigen',
    productShowcase: '🛒 Produktsortiment'
  },
  ja: {
    brand: 'NexCart',
    tagline: '精密に設計された最先端のハイテク電子機器',
    searchPlaceholder: 'スマートフォン、高性能ノートPC、オーディオを検索...',
    allCategories: '全カテゴリー',
    smartRecs: 'AIインテリジェント推奨',
    analytics: '販売データ統計',
    dashboard: 'マイダッシュボード',
    cart: 'ショッピングカート',
    login: 'ログイン',
    register: 'アカウント作成',
    logout: 'ログアウト',
    adminPanel: '管理者パネル',
    categories: 'カテゴリー',
    addToCart: 'カートに追加',
    outOfStock: '売り切れ',
    rating: '評価',
    inStock: '在庫あり',
    onlyLeft: '残りわずか',
    features: '主な性能',
    specs: '詳細仕様表',
    checkoutSummary: '決済内容の確認',
    orderTotal: 'ご注文合計',
    paymentDetails: 'セキュア決済ゲートウェイ',
    cardNumber: 'クレジットカード番号',
    expiryDate: '有効期限 (月/年)',
    shippingAddress: 'お届け先住所',
    fullName: '氏名（フルネーム）',
    addressLines: '住所（番地・マンション名）',
    city: '市区町村',
    postalCode: '郵便番号',
    country: '国',
    deliveryPartner: '配送ロジスティクス業者',
    placeOrder: '安全な決済を承認する',
    orderSuccess: '決済の承認が正常に完了しました！',
    orderSuccessDesc: 'ご注文は正常に処理されました。リアルタイムの在庫データが同期され、追跡が有効化されました。',
    trackingId: '配送追跡のお問い合わせ番号',
    estimatedDelivery: 'お届け予定日',
    customerCabinet: 'カスタマーダッシュボード',
    noOrders: '登録されたお取引履歴はまだありません。',
    orderId: '注文番号',
    orderDate: '日付',
    orderStatus: '配送状況',
    paymentStatus: '支払状況',
    carrier: '物流プロバイダー',
    trackShipment: '配送ルートを追跡',
    salesReporting: '財務売上詳細分析（管理者用）',
    totalSales: '総売上高',
    totalOrdersCount: '総注文数',
    lowStockAlerts: '品薄警告フラグ',
    salesByCategory: '製品カテゴリ別の販売売上 (INR)',
    dailyRevenueTrend: '日次売上曲線 (INR)',
    topPerformingItems: '最も売れている上位製品 (数量順)',
    notifications: 'リアルタイム通知',
    markAllRead: 'すべて既読にする',
    noNotifications: '通知はありません。すべて確認済みです。',
    toggleTheme: 'テーマカラー切り替え',
    languageLabel: '言語を選択',
    backToProducts: '商品一覧に戻る',
    recReasonPrompt: 'AIによるお勧め理由',
    confidenceScore: 'AI マッチング信頼度',
    aiEngineStatus: 'サーバーサイドに配置された Gemini 3.5-Flash が自動抽出',
    shippingProgress: '物流配送配達進捗ステータス',
    changeStatus: '配送ステータスの更新（管理コマンド）',
    updateStatusBtn: 'ステータス更新',
    filters: 'フィルター',
    reset: 'リセット',
    productCategory: '製品カテゴリー',
    allElectronics: 'すべての電子機器',
    minPrice: '最低価格',
    maxPrice: '最高価格',
    filterByBrand: 'ブランドで絞り込む',
    noBrandsFound: 'ブランドが見つかりません。',
    minimumRating: '最低評価',
    allRatings: 'すべての評価',
    andUp: '以上',
    authQuickDemo: 'クイックデモ資格情報:',
    authAutofill: '自動入力',
    authOrRegisterDesc: 'または、新規登録してアカウント管理ダッシュボードを開きます！',
    yourFullName: '氏名（フルネーム）',
    emailAddress: 'メールアドレス',
    securePassword: 'パスワードまたは暗証番号',
    alreadyRegistered: '登録済みですか？サインイン',
    createNewProfile: '代わりに新規プロファイルを作成する',
    verifiedAccountsFeedback: '検証済み購入者のレビュー',
    aggregateScore: '総合評価',
    basedOnReviews: '検証済みの個人・企業バイヤーによる評価です。',
    verifiedOwner: '検証済みの所有者',
    writeReview: 'レビューを書く：',
    yourRating: 'あなたの評価',
    yourExperience: 'あなたの体験',
    submitReviewBtn: '検証済みレビューを送信',
    reviewLocked: 'レビュー投稿ロック中',
    authRequiredToLeaveFeedback: 'レビューを投稿するにはログインが必要です。購入履歴の認証を行ってください。',
    feedbackWritesRequireVerification: 'レビューの投稿には製品の所有確認が必要です。該当製品をまず購入してください。',
    activeRecoup: 'アクティブな追跡',
    itemsPurchased: '購入済み商品',
    grossTotal: '総合計',
    recipientAddress: 'お届け先住所',
    showcaseTrackingUpdates: '追跡情報を表示するには注文を選択してください...',
    carrierLabel: '配送業者',
    trackingNumberLabel: '追跡番号',
    zeroUpfrontCharge: '事前費用なし',
    fastConfirmedShipping: '確実な迅速配送。安全な代引き確認。',
    paymentVerifyTxt: '決済確認中...',
    backToCart: 'カートに戻る',
    cartPriceLabel: '価格',
    viewSpecsDetail: '仕様の詳細を表示可能',
    productShowcase: '🛒 電子製品ショーケース'
  },
  te: {
    brand: 'NexCart',
    tagline: 'ఖచ్చితత్వంతో రూపొందించబడిన హై-టెక్ ఎలక్ట్రానిక్స్',
    searchPlaceholder: 'స్మార్ట్‌ఫోన్‌లు, హై-స్పెక్ ల్యాప్‌టాప్‌లు, ఆడియో గేర్ వెతకండి...',
    allCategories: 'అన్ని విభాగాలు',
    smartRecs: 'స్మార్ట్ AI సిఫార్సులు',
    analytics: 'సేల్స్ విశ్లేషణ',
    dashboard: 'డాష్‌బోర్డ్',
    cart: 'షాపింగ్ కార్ట్',
    login: 'లాగిన్',
    register: 'సైన్ అప్',
    logout: 'లాగౌట్',
    adminPanel: 'అడ్మిన్ ప్యానెల్',
    categories: 'విభాగాలు',
    addToCart: 'కార్ట్‌కు జోడించు',
    outOfStock: 'అయిపోయింది',
    rating: 'రేటింగ్',
    inStock: 'స్టాక్‌లో ఉంది',
    onlyLeft: 'మాत्राమే మిగిలి ఉన్నాయి',
    features: 'ముఖ్య లక్షణాలు',
    specs: 'సాంకేతిక వివరాలు',
    checkoutSummary: 'చెక్అవుట్ సారాంశం',
    orderTotal: 'ఆర్డర్ మొత్తం',
    paymentDetails: 'సురక్షిత చెల్లింపు గేట్‌వే',
    cardNumber: 'క్రెడిట్ కార్డ్ నంబర్',
    expiryDate: 'గడువు తేదీ (MM/YY)',
    shippingAddress: 'షిప్పింగ్ చిరునామా',
    fullName: 'పూర్తి పేరు',
    addressLines: 'వీధి చిరునామా',
    city: 'నగరం',
    postalCode: 'పిన్ కోడ్',
    country: 'దేశం',
    deliveryPartner: 'లాజిస్టిక్స్ భాగస్వామి',
    placeOrder: 'సురక్షిత చెల్లింపును ప్రాధికారించు',
    orderSuccess: 'చెల్లింపు విజయవంతంగా ప్రాధికారించబడింది!',
    orderSuccessDesc: 'మీ ఆర్డర్ ప్రాసెస్ చేయబడింది. నిజ-సమయ స్టాక్ స్థాయిలు నవీకరించబడ్డాయి మరియు లాజిస్టిక్స్ ట్రాకింగ్ ప్రత్యక్షంగా ఉంది.',
    trackingId: 'లాజిస్టిక్స్ ట్రాకింగ్ ID',
    estimatedDelivery: 'అంచనా డెలివరీ',
    customerCabinet: 'కస్టమర్ డాష్‌బోర్డ్',
    noOrders: 'మీకు ఇంకా ఎలాంటి లావాదేవీలు నమోదు కాలేదు.',
    orderId: 'ఆర్డర్ ID',
    orderDate: 'తేదీ',
    orderStatus: 'షిప్పింగ్ స్థితి',
    paymentStatus: 'చెల్లింపు',
    carrier: 'లాజిస్టిక్స్ కొరియర్',
    trackShipment: 'షిప్పింగ్ మార్గాన్ని ట్రాక్ చేయండి',
    salesReporting: 'అడ్మిన్ ఆర్థిక అమ్మకాల విశ్లేషణ',
    totalSales: 'మొత్తం అమ్మకాల ఆదాయం',
    totalOrdersCount: 'మొత్తం ఆర్డర్లు',
    lowStockAlerts: 'తక్కువ స్టాక్ హెచ్చరిక ట్రిగ్గర్',
    salesByCategory: 'ఉற்பత్తి విభాగాల వారీగా అమ్మకాల ఆదాయం (INR)',
    dailyRevenueTrend: 'రోజువారీ ఆదాయ వక్రరేఖ (INR)',
    topPerformingItems: 'అధికంగా అమ్ముడైన ఉత్పత్తులు (యూనిట్ల వారీగా)',
    notifications: 'నిజ-సమయ నోటిఫికేషన్లు',
    markAllRead: 'అన్నీ చదివినట్లుగా గుర్తు పెట్టు',
    noNotifications: 'నోటిఫికేషన్లు ఏమీ లేవు.',
    toggleTheme: 'దృశ్య థీమ్‌ను మార్చండి',
    languageLabel: 'Select Language',
    backToProducts: 'ప్రదర్శనకు తిరిగి వెళ్ళు',
    recReasonPrompt: 'AI సిఫార్సు చేసిన కారణం',
    confidenceScore: 'AI మ్యాచింగ్ కాన్ఫिడెన్స్',
    aiEngineStatus: 'సర్వర్-సైడ్ జెమినీ 3.5-ఫ్లాష్ ద్వారా ఆధారితం',
    shippingProgress: 'ప్రామాణిక కొరియర్ రవాణా పురోగతి',
    changeStatus: 'రవాణా స్థితిని సవరించండి (అడ్మిన్ కమాండ్)',
    updateStatusBtn: 'స్థితిని నవీకరించండి',
    filters: 'ఫిల్టర్లు',
    reset: 'రీసెట్',
    productCategory: 'ఉற்பత్తి వర్గం',
    allElectronics: 'అన్ని ఎలక్ట్రానిక్స్',
    minPrice: 'కనిష్ట ధర',
    maxPrice: 'గరిష్ట ధర',
    filterByBrand: 'బ్రాండ్ ద్వారా వడపోత',
    noBrandsFound: 'బ్రాండ్లు కనుగొనబడలేదు.',
    minimumRating: 'కనిష్ట రేటింగ్',
    allRatings: 'అన్ని రేటింగ్‌లు',
    andUp: 'మరియు అంతకంటే ఎక్కువ',
    authQuickDemo: 'త్వరిత డెమో ఆధారాలు:',
    authAutofill: 'ఆటోఫిల్',
    authOrRegisterDesc: 'లేదా స్వాగత నోటిఫికేషన్‌లను పొందడానికి కొత్త ప్రొఫైల్‌ను నమోదు చేయండి!',
    yourFullName: 'మీ పూర్తి పేరు',
    emailAddress: 'ఈమెయిల్ చిరునామా',
    securePassword: 'సురక్షిత పిన్ / పాస్‌వర్డ్',
    alreadyRegistered: 'ఇప్పటికే నమోదు చేసుకున్నారా? సైన్ ఇన్',
    createNewProfile: 'బదులుగా సరికొత్త ప్రొఫైల్ సృష్టించండి',
    verifiedAccountsFeedback: 'ధృవీకరించబడిన ఖాతాల అభిప్రాయం',
    aggregateScore: 'సంచిత రేటింగ్',
    basedOnReviews: 'ధృవీకరించబడిన కొనుగోలుదారుల నిజమైన సమీక్షలపై ఆధారపడి ఉంటుంది.',
    verifiedOwner: 'ధృవీకరించబడిన యజమాని',
    writeReview: 'దీని కోసం సమీక్ష రాయండి',
    yourRating: 'మీ రేటింగ్',
    yourExperience: 'మీ అనుభవం',
    submitReviewBtn: 'ధృవీకరించబడిన సమీక్షను సమర్పించండి',
    reviewLocked: 'సమీక్ష రాయడం లాక్ చేయబడింది',
    authRequiredToLeaveFeedback: 'అభిప్రాయాన్ని తెలియజేయడానికి లాగిన్ అవ్వాలి. దయచేసి సైన్ ఇన్ చేయండి, ఐటమ్ కొనుగోలు చేయండి.',
    feedbackWritesRequireVerification: 'అభిప్రాయం రాయడానికి ఖచ్చితంగా ఉత్పత్తిని కొనుగోలు చేసి ఉండాలి. ఆర్డర్ మొదట ఉంచండి.',
    activeRecoup: 'క్రియాశీల ట్రాకింగ్',
    itemsPurchased: 'కొనుగోలు చేసిన వస్తువులు',
    grossTotal: 'మొత్తం మొత్తం',
    recipientAddress: 'గ్రహీత చిరునామా',
    showcaseTrackingUpdates: 'ట్రాకింగ్ అప్‌డేట్స్ కోసం ఆర్డర్‌ను ఎంచుకోండి...',
    carrierLabel: 'క్యారియర్',
    trackingNumberLabel: 'ట్రాకింగ్ నంబర్',
    zeroUpfrontCharge: 'ముందస్తు ఛార్జీ లేదు',
    fastConfirmedShipping: 'వేగవంతమైన షిప్పింగ్. సురక్షిత క్యాష్ ఆన్ డెలివరీ.',
    paymentVerifyTxt: 'చెల్లింపును ధృవీకరిస్తోంది...',
    backToCart: 'కార్ట్‌కి తిరిగి వెళ్ళు',
    cartPriceLabel: 'ధర',
    viewSpecsDetail: 'వివరాల స్పెసిఫికేషన్లు చూడండి',
    productShowcase: '🛒 ఉత్పత్తి ప్రదర్శన'
  },
  hi: {
    brand: 'NexCart',
    tagline: 'सटीकता से तैयार की गई हाई-टेक इलेक्ट्रॉनिक्स',
    searchPlaceholder: 'स्मार्टफोन, हाई-स्पेक लैपटॉप, ऑडियो गियर खोजें...',
    allCategories: 'सभी श्रेणियां',
    smartRecs: 'स्मार्ट एआई सिफारिशें',
    analytics: 'बिक्री विश्लेषण',
    dashboard: 'डैशबोर्ड',
    cart: 'शॉपिंग कार्ट',
    login: 'लॉग इन करें',
    register: 'साइन अप करें',
    logout: 'लॉग आउट',
    adminPanel: 'प्रशासक पैनल',
    categories: 'श्रेणियाँ',
    addToCart: 'कार्ट में जोड़ें',
    outOfStock: 'बिक गया',
    rating: 'रेटिंग',
    inStock: 'स्टॉक में है',
    onlyLeft: 'केवल बचे हैं',
    features: 'मुख्य विशेषताएं',
    specs: 'तकनीकी विनिर्देश',
    checkoutSummary: 'चेकआउट सारांश',
    orderTotal: 'कुल ऑर्डर',
    paymentDetails: 'सुरक्षित भुगतान गेटवे',
    cardNumber: 'क्रेडिट कार्ड नंबर',
    expiryDate: 'समाप्ति तिथि (MM/YY)',
    shippingAddress: 'शिपिंग का पता',
    fullName: 'पूरा नाम',
    addressLines: 'सड़क का पता',
    city: 'शहर',
    postalCode: 'पिन कोड',
    country: 'देश',
    deliveryPartner: 'लॉजिस्टिक्स भागीदार',
    placeOrder: 'सुरक्षित भुगतान अधिकृत करें',
    orderSuccess: 'भुगतान सफलतापूर्वक अधिकृत किया गया!',
    orderSuccessDesc: 'आपका ऑर्डर संसाधित कर दिया गया है। वास्तविक समय में स्टॉक स्तर अपडेट कर दिए गए हैं और लॉजिस्टिक्स ट्रैकिंग लाइव है।',
    trackingId: 'लॉजिस्टिक्स ट्रैकिंग आईडी',
    estimatedDelivery: 'अनुमानित डिलीवरी',
    customerCabinet: 'ग्राहक डैशबोर्ड',
    noOrders: 'आपके पास अभी तक कोई पंजीकृत लेनदेन नहीं है।',
    orderId: 'ऑर्डर आईडी',
    orderDate: 'दिनांक',
    orderStatus: 'शिपिंग स्थिति',
    paymentStatus: 'भुगतान',
    carrier: 'लॉजिस्टिक्स कूरियर',
    trackShipment: 'शिपिंग मार्ग ट्रैक करें',
    salesReporting: 'व्यवस्थापक वित्तीय बिक्री विश्लेषण',
    totalSales: 'सकल बिक्री राजस्व',
    totalOrdersCount: 'कुल ऑर्डर',
    lowStockAlerts: 'कम स्टॉक चेतावनी ट्रिगर',
    salesByCategory: 'उत्पाद श्रेणी के अनुसार बिक्री राजस्व (INR)',
    dailyRevenueTrend: 'दैनिक राजस्व वक्र (INR)',
    topPerformingItems: 'सर्वश्रेष्ठ प्रदर्शन करने वाले उत्पाद (बेची गई इकाइयाँ)',
    notifications: 'वास्तविक समय सूचनाएं',
    markAllRead: 'सभी को पढ़े गए के रूप में चिह्नित करें',
    noNotifications: 'आप पूरी तरह से अपडेट हैं।',
    toggleTheme: 'विज़ुअल थीम बदलें',
    languageLabel: 'Select Language',
    backToProducts: 'शोकेस पर वापस जाएं',
    recReasonPrompt: 'एआई द्वारा अनुशंसित कारण',
    confidenceScore: 'एआई मिलान आत्मविश्वास',
    aiEngineStatus: 'सर्वर-साइड जेमिनी 3.5-फ्लैश द्वारा संचालित',
    shippingProgress: 'मानक कूरियर प्रेषण प्रगति',
    changeStatus: 'पारगमन स्थिति संशोधित करें (व्यवस्थापक कमान)',
    updateStatusBtn: 'स्थिति अपडेट करें',
    filters: 'फ़िल्टर',
    reset: 'रीसेट',
    productCategory: 'उत्पाद श्रेणी',
    allElectronics: 'सभी इलेक्ट्रॉनिक्स',
    minPrice: 'न्यूनतम मूल्य',
    maxPrice: 'अधिकतम मूल्य',
    filterByBrand: 'ब्रांड द्वारा फ़िल्टर',
    noBrandsFound: 'कोई ब्रांड नहीं मिला।',
    minimumRating: 'न्यूनतम रेटिंग',
    allRatings: 'सभी रेटिंग',
    andUp: 'और अधिक',
    authQuickDemo: 'त्वरित क्रेडेंशियल्स दर्ज करें:',
    authAutofill: 'ऑटोफ़िल',
    authOrRegisterDesc: 'या पहली स्वागत सूचनाएं प्राप्त करने के लिए नया प्रोफ़ाइल पंजीकृत करें!',
    yourFullName: 'आपका पूरा नाम',
    emailAddress: 'ईमेल पता',
    securePassword: 'सुरक्षित पिन / पासवर्ड',
    alreadyRegistered: 'पहले से ही पंजीकृत हैं? साइन इन करें',
    createNewProfile: 'इसके स्थान पर नया प्रोफ़ाइल बनाएं',
    verifiedAccountsFeedback: 'सत्यापित ग्राहक समीक्षाएं',
    aggregateScore: 'संचयी स्कोर',
    basedOnReviews: 'सत्यापित खरीददारों की वास्तविक समीक्षाओं पर आधारित।',
    verifiedOwner: 'सत्यापित स्वामी',
    writeReview: 'इसके लिए अपनी समीक्षा लिखें',
    yourRating: 'आपकी रेटिंग',
    yourExperience: 'आपका अनुभव',
    submitReviewBtn: 'सत्यापित समीक्षा जमा करें',
    reviewLocked: 'समीक्षा लिखना बंद है',
    authRequiredToLeaveFeedback: 'समीक्षा छोड़ने के लिए लॉगिन आवश्यक है। कृपया साइन इन करें, खरीद पूरी करें।',
    feedbackWritesRequireVerification: 'समीक्षा के लिए स्वामित्व का सत्यापन चाहिए। पहले इस आइटम का ऑर्डर करें।',
    activeRecoup: 'सक्रिय ट्रैकिंग',
    itemsPurchased: 'खरीदी गई वस्तुएं',
    grossTotal: 'कुल योग',
    recipientAddress: 'प्राप्तकर्ता का पता',
    showcaseTrackingUpdates: 'ट्रैकिंग अपडेट देखने के लिए ऑर्डर चुनें...',
    carrierLabel: 'वाहक',
    trackingNumberLabel: 'ट्रैकिंग नंबर',
    zeroUpfrontCharge: 'कोई पूर्व शुल्क नहीं',
    fastConfirmedShipping: 'तेज़ शिपिंग पुष्टि। सुरक्षित सीओडी सत्यापन।',
    paymentVerifyTxt: 'भुगतान की पुष्टि की जा रही है...',
    backToCart: 'कार्ट पर वापस जाएं',
    cartPriceLabel: 'कीमत',
    viewSpecsDetail: 'विस्तृत विवरण देखें',
    productShowcase: '🛒 उत्पाद शोकेस'
  },
  ta: {
    brand: 'NexCart',
    tagline: 'துல்லியமாக வடிவமைக்கப்பட்ட ஹை-டெக் எலக்ட்ரானிக்ஸ்',
    searchPlaceholder: 'ஸ்மார்ட்போன்கள், ஹை-ஸ்பெக் லேப்டாப்கள், ஆடியோ கருவிகளைத் தேடுங்கள்...',
    allCategories: 'அனைத்து பிரிவுகள்',
    smartRecs: 'smart AI பரிந்துரைகள்',
    analytics: 'விற்பனை பகுப்பாய்வு',
    dashboard: 'டாஷ்போர்டு',
    cart: 'ஷாப்பிங் கார்ட்',
    login: 'உள்நுழை',
    register: 'பதிவு செய்',
    logout: 'வெளியேறு',
    adminPanel: 'நிர்வாக குழு',
    categories: 'பிரிவுகள்',
    addToCart: 'வண்டியில் சேர்',
    outOfStock: 'விற்பனையாகிவிட்டது',
    rating: 'மதிப்பீடு',
    inStock: 'கையிருப்பில் உள்ளது',
    onlyLeft: 'மட்டுமே மீதமுள்ளது',
    features: 'முக்கிய அம்சங்கள்',
    specs: 'தொழில்நுட்ப விவரக்குறிப்புகள்',
    checkoutSummary: 'செக்அவுட் சுருக்கம்',
    orderTotal: 'ஆர்டர் மொத்தம்',
    paymentDetails: 'பாதுகாப்பான கட்டண நுழைவாயில்',
    cardNumber: 'கிரெடிட் கார்ட் எண்',
    expiryDate: 'காலாவதி தேதி (MM/YY)',
    shippingAddress: 'ஷிப்பிங் முகவரி',
    fullName: 'முழு பெயர்',
    addressLines: 'தெரு முகவரி',
    city: 'நகரம்',
    postalCode: 'அஞ்சல் குறியீடு',
    country: 'நாடு',
    deliveryPartner: 'லாஜிஸ்டிக்ஸ் கூட்டாளி',
    placeOrder: 'பாதுகாப்பான கட்டணத்தை அங்கீகரி',
    orderSuccess: 'கட்டணம் வெற்றிகரமாக அங்கீகரிக்கப்பட்டது!',
    orderSuccessDesc: 'உங்கள் ஆர்டர் செயலாக்கப்பட்டது. நிகழ்நேர இருப்பு நிலைகள் புதுப்பிக்கப்பட்டு, லாஜிஸ்டிக்ஸ் கண்காணிப்பு நேரலையில் உள்ளது.',
    trackingId: 'லாஜிஸ்டிக்ஸ் கண்காணிப்பு ஐடி',
    estimatedDelivery: 'மதிப்பிடப்பட்ட விநியோகம்',
    customerCabinet: 'வாடிக்கையாளர் டாஷ்போர்டு',
    noOrders: 'உங்களுக்கு இதுவரை பரிவர்த்தனைகள் எதுவும் இல்லை.',
    orderId: 'ஆர்டர் ஐடி',
    orderDate: 'தேதி',
    orderStatus: 'ஷிப்பிங் நிலை',
    paymentStatus: 'கட்டணம்',
    carrier: 'லாஜிஸ்டிக்ஸ் கூரியர்',
    trackShipment: 'ஷிப்பிங் பாதையை கண்காணிக்கவும்',
    salesReporting: 'நிர்வாக நிதி விற்பனை பகுப்பாய்வு',
    totalSales: 'மொத்த விற்பனை வருவாய்',
    totalOrdersCount: 'மொத்த ஆர்டர்கள்',
    lowStockAlerts: 'குறைந்த இருப்பு எச்சரிக்கை தூண்டுதல்',
    salesByCategory: 'தயாரிப்பு வகையின்படி விற்பனை வருவாய் (INR)',
    dailyRevenueTrend: 'தினசரி வருவாய் வளைவு (INR)',
    topPerformingItems: 'சிறந்த செயல்திறன் கொண்ட தயாரிப்புகள் (விற்பனையான அலகுகள் மூலம்)',
    notifications: 'நிகழ்நேர அறிவிப்புகள்',
    markAllRead: 'அனைத்தையும் படித்ததாகக் குறிக்கவும்',
    noNotifications: 'அறிவிப்புகள் எதுவும் இல்லை.',
    toggleTheme: 'காட்சி தீம் மாற்றவும்',
    languageLabel: 'Select Language',
    backToProducts: 'காட்சிக்குத் திரும்பு',
    recReasonPrompt: 'AI பரிந்துரைத்த காரணம்',
    confidenceScore: 'AI பொருத்தம் நம்பிக்கை',
    aiEngineStatus: 'சர்வர் பக்க ஜெமினி 3.5-ஃப்ளாஷ் மூலம் இயக்கப்படுகிறது',
    shippingProgress: 'நிலையான கூரியர் அனுப்புதல் முன்னேற்றம்',
    changeStatus: 'போக்குவரத்து நிலையை மாற்றவும் (நிர்வாக கட்டளை)',
    updateStatusBtn: 'நிலையைப் புதுப்பி',
    filters: 'வடிகட்டிகள்',
    reset: 'மீட்டமை',
    productCategory: 'தயாரிப்பு வகை',
    allElectronics: 'அனைத்து மின்னணு சாதனங்கள்',
    minPrice: 'குறைந்தபட்ச விலை',
    maxPrice: 'அதிகபட்ச விலை',
    filterByBrand: 'பிராண்ட் மூலம் வடிகட்டு',
    noBrandsFound: 'பிராண்டுகள் எதுவும் இல்லை.',
    minimumRating: 'குறைந்தபட்ச மதிப்பீடு',
    allRatings: 'அனைத்து மதிப்பீடுகள்',
    andUp: 'மற்றும் அதற்கு மேல்',
    authQuickDemo: 'விரைவான டெமோ சான்றுகள்:',
    authAutofill: 'தானியங்கு நிரப்பல்',
    authOrRegisterDesc: 'அல்லது புதிய கணக்கை உருவாக்கி வரவேற்பு அறிவிப்பைத் தூண்டவும்!',
    yourFullName: 'உங்கள் முழு பெயர்',
    emailAddress: 'மின்னஞ்சல் முகவரி',
    securePassword: 'பாதுகாப்பான பின் / கடவுச்சொல்',
    alreadyRegistered: 'ஏற்கனவே பதிவு செய்யப்பட்டுள்ளதா? உள்நுழைக',
    createNewProfile: 'அதற்குப் பதிலாக புதிய சுயவிவரத்தை உருவாக்கவும்',
    verifiedAccountsFeedback: 'சரிபார்க்கப்பட்ட கணக்குகளின் கருத்து',
    aggregateScore: 'ஒட்டுமொத்த மதிப்பெண்',
    basedOnReviews: 'சரிபார்க்கப்பட்ட வாங்குபவர்களின் உண்மையான கருத்துகளின் அடிப்படையில்.',
    verifiedOwner: 'சரிபார்க்கப்பட்ட உரிமையாளர்',
    writeReview: 'இதற்கான உங்கள் மதிப்புரையை எழுதவும்',
    yourRating: 'உங்கள் மதிப்பீடு',
    yourExperience: 'உங்கள் அனுபவம்',
    submitReviewBtn: 'சரிபார்க்கப்பட்ட மதிப்புரையை சமர்ப்பிக்கவும்',
    reviewLocked: 'மதிப்புரை எழுதுவது பூட்டப்பட்டுள்ளது',
    authRequiredToLeaveFeedback: 'மதிப்புரை எழுத உள்நுழைவு தேவை. தயாக உள்நுழைந்து, பொருளை வாங்கி, ரசீதை சரிபார்க்கவும்.',
    feedbackWritesRequireVerification: 'மதிப்புரைகள் எழுத பொருளை வாங்கியது அவசியம். முதலில் இதற்கு ஒரு ஆர்டர் செய்யுங்கள்.',
    activeRecoup: 'செயலில் உள்ள கண்காணிப்பு',
    itemsPurchased: 'வாங்கிய பொருட்கள்',
    grossTotal: 'மொத்த தொகை',
    recipientAddress: 'பெறுநரின் முகவரி',
    showcaseTrackingUpdates: 'கண்காணிப்பு புதுப்பிப்புகளைப் பார்க்க ஆர்டரைத் தேர்ந்தெடுக்கவும்...',
    carrierLabel: 'கூரியர்',
    trackingNumberLabel: 'கண்காணிப்பு எண்',
    zeroUpfrontCharge: 'முன்கூட்டிய கட்டணம் இல்லை',
    fastConfirmedShipping: 'விரைவான கப்பல் போக்குவரத்து. பாதுகாப்பான கேஷ் ஆன் டெலிவரி.',
    paymentVerifyTxt: 'கட்டணம் சரிபார்க்கப்படுகிறது...',
    backToCart: 'கார்ட்டிற்கு திரும்பு',
    cartPriceLabel: 'விலை',
    viewSpecsDetail: 'விவரக்குறிப்புகளைப் பார்க்கவும்',
    productShowcase: '🛒 தயாரிப்பு காட்சி'
  }
};
